<?= $this->start('content') ?>

<main class="paper-page">
    <section class="paper-page-header">
        <div class="paper-kicker"><i class="icon-layers"></i> Generated Page</div>
        <h1><?= escape($title ?? 'Watch Watch Tv') ?></h1>
        <p>This page was generated by the Paper-PHPFramework controller CLI.</p>
        <div class="paper-actions">
            <a class="paper-btn primary" href="/"><i class="icon-home"></i> Home</a>
        </div>
    </section>

    <section class="paper-panel">
        <div class="paper-panel-head">
            <strong>Watch Watch Tv</strong>
            <span class="paper-pill">Ready</span>
        </div>
        <div class="paper-panel-body">
            <span>Build this page from <strong>Watch Watch Tv</strong>.</span>
        </div>
    </section>
</main>

<?= $this->end() ?>
